name: kustomize
description: run kustomize build
inputs:
  kustomization:
    description: glob patterns to kustomization.yaml
    required: true
  extra-files:
    description: glob patterns to extra files to copy
    required: false
  base-directory:
    description: base directory to compute a relative path of kustomization.yaml
    required: true
    default: ${{ github.workspace }}
  retry-max-attempts:
    description: max attempts of retry to run kustomize (0 = no retry)
    required: true
    default: '2'
  retry-wait-ms:
    description: wait before retry kustomize in milliseconds
    required: true
    default: '2000'
  max-process:
    description: max number of kustomize processes
    required: true
    default: '5'
  write-individual-files:
    description: set true to write individual files
    required: true
    default: 'false'
  ignore-kustomize-error:
    description: set true to ignore kustomize errors
    required: true
    default: 'false'
  error-comment:
    description: post a comment on error
    required: true
    default: 'false'
  error-comment-header:
    description: header in a comment to post on error
    required: false
    default: |
      ## :x: kustomize error
  error-comment-footer:
    description: footer in a comment to post on error
    required: false
    default: |
      <!-- kustomization-action -->
  token:
    description: GitHub token to post a comment on error
    required: true
    default: ${{ github.token }}
outputs:
  directory:
    description: directory to results of kustomize build
  files:
    description: multi-line string of files generated by kustomize build
runs:
  using: 'node16'
  main: 'dist/index.js'
