name: kustomize
description: run kustomize build
inputs:
  pattern:
    description: glob patterns to kustomization.yaml
    required: true
  base-directory:
    description: base directory to compute a relative path of kustomization.yaml
    required: true
    default: ${{ github.workspace }}
  max-process:
    description: max number of kustomize processes
    required: true
    default: '5'
outputs:
  directory:
    description: directory to results of kustomize build
runs:
  using: 'node12'
  main: 'dist/index.js'
