name: kustomize
description: Run kustomize build in parallel
inputs:
  kustomization:
    description: Glob patterns to kustomization.yaml
    required: true
  extra-files:
    description: Glob patterns to extra files to copy
    required: false
  kustomize-build-args:
    description: Extra args to kustomize build command (multiline)
    required: false
  base-directory:
    description: Base directory to compute a relative path of kustomization.yaml
    required: true
    default: ${{ github.workspace }}
  output-directory:
    description: Directory to write kustomize build results (defaults to a temporary directory)
    required: false
  retry-max-attempts:
    description: Max attempts of retry to run kustomize (0 = no retry)
    required: true
    default: '2'
  retry-wait-ms:
    description: Wait before retry kustomize in milliseconds
    required: true
    default: '2000'
  max-process:
    description: Max number of kustomize processes
    required: true
    default: '5'
  write-individual-files:
    description: If true, write individual files
    required: true
    default: 'false'
  ignore-kustomize-error:
    description: If true, ignore kustomize errors
    required: true
    default: 'false'
  error-comment:
    deprecationMessage: Use pretty-errors instead. See https://github.com/int128/kustomize-action#error-comment
    description: Post a comment on error
    required: true
    default: 'false'
  error-comment-header:
    deprecationMessage: Use pretty-errors instead. See https://github.com/int128/kustomize-action#error-comment
    description: Header in a comment to post on error
    required: false
    default: |
      ## :x: kustomize error
  error-comment-footer:
    deprecationMessage: Use pretty-errors instead. See https://github.com/int128/kustomize-action#error-comment
    description: Footer in a comment to post on error
    required: false
    default: |
      <!-- kustomization-action -->
  token:
    description: GitHub token to post a comment on error
    required: true
    default: ${{ github.token }}
outputs:
  directory:
    description: Directory to results of kustomize build
  files:
    description: Multi-line string of files generated by kustomize build
  raw-errors:
    description: Multi-line string of errors generated by kustomize build
  pretty-errors:
    description: Pretty formatted errors of kustomize build
runs:
  using: 'node20'
  main: 'dist/index.js'
