name: kustomize-diff-action
description: run kustomize build and diff between head and base ref

inputs:
  kustomization:
    description: glob patterns to kustomization.yaml
    required: true
  write-individual-files:
    description: set true to write individual files (optional)
  token:
    description: GitHub token (optional)
    required: true
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      with:
        ref: ${{ github.base_ref }}
        path: _base_ref

    - uses: int128/hide-comment-action@2b9b0f2c6f482cb70511b4342744d3622f9e23eb # v1.30.0
      with:
        token: ${{ inputs.token }}
        ends-with: |
          <!-- kustomize-action -->
          <!-- diff-action -->

    - uses: int128/kustomize-action@78a1dd3a437c7c1247ab7a3e053983fd56a3d956 # v1.54.0
      id: kustomize-head
      with:
        token: ${{ inputs.token }}
        write-individual-files: ${{ inputs.write-individual-files }}
        kustomization: ${{ inputs.kustomization }}

    - uses: int128/kustomize-action@78a1dd3a437c7c1247ab7a3e053983fd56a3d956 # v1.54.0
      id: kustomize-base
      with:
        token: ${{ inputs.token }}
        base-directory: _base_ref
        write-individual-files: ${{ inputs.write-individual-files }}
        kustomization: ${{ inputs.kustomization }}
        ignore-kustomize-error: true

    - uses: int128/diff-action@cef77ef2442d5c6b0c622a9f6e2e521f9c6cb270 # v1.37.0
      with:
        token: ${{ inputs.token }}
        base: ${{ steps.kustomize-base.outputs.directory }}
        head: ${{ steps.kustomize-head.outputs.directory }}
