name: kustomize-diff-action
description: run kustomize build and diff between head and base ref

inputs:
  kustomization:
    description: glob patterns to kustomization.yaml
    required: true
  write-individual-files:
    description: set true to write individual files (optional)
  token:
    description: GitHub token (optional)
    required: true
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      with:
        ref: ${{ github.base_ref }}
        path: _base_ref

    - uses: int128/hide-comment-action@5aa4ad6cf762098ebdc5d3c046e9e1fb35fe5ce8 # v1.23.0
      with:
        token: ${{ inputs.token }}
        ends-with: |
          <!-- kustomize-action -->
          <!-- diff-action -->

    - uses: int128/kustomize-action@77cb30ebfef484fd4f3bb2f06da6130477e7c3d6 # v1.27.0
      id: kustomize-head
      with:
        token: ${{ inputs.token }}
        write-individual-files: ${{ inputs.write-individual-files }}
        kustomization: ${{ inputs.kustomization }}

    - uses: int128/kustomize-action@77cb30ebfef484fd4f3bb2f06da6130477e7c3d6 # v1.27.0
      id: kustomize-base
      with:
        token: ${{ inputs.token }}
        base-directory: _base_ref
        write-individual-files: ${{ inputs.write-individual-files }}
        kustomization: ${{ inputs.kustomization }}
        ignore-kustomize-error: true

    - uses: int128/diff-action@757ae2d0f4e2b66003f232f7ebd6ca998ff2b81b # v1.17.0
      with:
        token: ${{ inputs.token }}
        base: ${{ steps.kustomize-base.outputs.directory }}
        head: ${{ steps.kustomize-head.outputs.directory }}
