name: kustomize-diff-test

on:
  pull_request:
    paths:
      - .github/workflows/diff.yaml
  push:
    branches:
      - main
    paths:
      - .github/workflows/diff.yaml

jobs:
  diff:
    uses: ./.github/workflows/diff.yaml
    with:
      kustomization: tests/fixtures/overlays/*/kustomization.yaml
